[package]
name = "floracad"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dms-coordinates = "1.1.0"
dxf = { version = "0.5.0", features = ["serialize"] }
eqsolver = "0.1.1"
geo = "0.24.1"
serde = "1.0.158"
